# IIC-3670 NLP UC

- Versiones de librerías, python 3.8.10

- numpy 1.20.3
- nltk 3.7
- spacy 3.5.1
- sklearn 
- keras 2.9.0
- tensorflow 2.9.1


In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

C:\Users\marce\AppData\Local\Temp\ipykernel_30276\3777615979.py:1: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML


In [2]:
!python3 -m spacy download es_core_news_md

  Using cached https://github.com/explosion/spacy-models/releases/download/es_core_news_md-3.5.0/es_core_news_md-3.5.0-py3-none-any.whl (42.3 MB)
[+] Download and installation successful
You can now load the package via spacy.load('es_core_news_md')



[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: C:\Users\marce\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [3]:
import spacy

sp = spacy.load('es_core_news_md')

In [4]:
doc = sp("Paredes bate el record de Chamaco Valdes y deja a la U en zona de descenso")

In [5]:
for word in doc:
    print(str(word.text).ljust(15) + str(word.pos_).ljust(15))

Paredes        PROPN          
bate           VERB           
el             DET            
record         NOUN           
de             ADP            
Chamaco        PROPN          
Valdes         PROPN          
y              CCONJ          
deja           VERB           
a              ADP            
la             DET            
U              PROPN          
en             ADP            
zona           NOUN           
de             ADP            
descenso       NOUN           


In [6]:
for entity in doc.ents:
    print(entity.text + ' - ' + entity.label_ + ' - ' + str(spacy.explain(entity.label_)))

Paredes - PER - Named person or family.
Chamaco Valdes - PER - Named person or family.
U - MISC - Miscellaneous entities, e.g. events, nationalities, products or works of art


In [7]:
from spacy import displacy

displacy.render(doc, style='ent', jupyter=True)

Building a POS tagger from scratch

In [5]:
import nltk
 
tagged_sentences = nltk.corpus.treebank.tagged_sents()
 
print(tagged_sentences[0])
print("Tagged sentences: ", len(tagged_sentences))
print("Tagged words:", len(nltk.corpus.treebank.tagged_words()))

[('Pierre', 'NNP'), ('Vinken', 'NNP'), (',', ','), ('61', 'CD'), ('years', 'NNS'), ('old', 'JJ'), (',', ','), ('will', 'MD'), ('join', 'VB'), ('the', 'DT'), ('board', 'NN'), ('as', 'IN'), ('a', 'DT'), ('nonexecutive', 'JJ'), ('director', 'NN'), ('Nov.', 'NNP'), ('29', 'CD'), ('.', '.')]
Tagged sentences:  3914
Tagged words: 100676


In [6]:
import numpy as np
 
sentences, sentence_tags =[], [] 
for tagged_sentence in tagged_sentences:
    sentence, tags = zip(*tagged_sentence)
    sentences.append(np.array(sentence))
    sentence_tags.append(np.array(tags))
 
print(sentences[1])
print(sentence_tags[1])

['Mr.' 'Vinken' 'is' 'chairman' 'of' 'Elsevier' 'N.V.' ',' 'the' 'Dutch'
 'publishing' 'group' '.']
['NNP' 'NNP' 'VBZ' 'NN' 'IN' 'NNP' 'NNP' ',' 'DT' 'NNP' 'VBG' 'NN' '.']


In [7]:
from sklearn.model_selection import train_test_split
 
(train_sentences, test_sentences,  train_tags,  test_tags) = train_test_split(sentences, sentence_tags, test_size=0.15)

In [8]:
words, tags = set([]), set([])
 
for s in train_sentences:
    for w in s:
        words.add(w.lower())
 
for ts in train_tags:
    for t in ts:
        tags.add(t)
 
word2index = {w: i + 2 for i, w in enumerate(list(words))}
word2index['-PAD-'] = 0  # The special value used for padding
word2index['-OOV-'] = 1  # The special value used for OOVs
 
tag2index = {t: i + 1 for i, t in enumerate(list(tags))}
tag2index['-PAD-'] = 0   # The special value used to padding


In [9]:
print(tags)

{'-LRB-', 'VBN', 'NNP', 'LS', '.', 'CC', 'RBS', 'FW', 'VBP', 'IN', 'VBD', '``', '-NONE-', 'JJR', 'MD', 'NN', 'CD', 'RP', "''", 'RB', 'EX', 'WDT', 'UH', '$', 'JJ', 'PRP$', 'JJS', 'VBG', 'NNPS', 'WP', 'SYM', 'POS', 'TO', 'PRP', 'PDT', 'WRB', ':', 'NNS', 'VB', 'DT', 'VBZ', '-RRB-', '#', 'WP$', 'RBR', ','}


In [10]:
train_sentences_X, test_sentences_X, train_tags_y, test_tags_y = [], [], [], []
 
for s in train_sentences:
    s_int = []
    for w in s:
        try:
            s_int.append(word2index[w.lower()])
        except KeyError:
            s_int.append(word2index['-OOV-'])
 
    train_sentences_X.append(s_int)
 
for s in test_sentences:
    s_int = []
    for w in s:
        try:
            s_int.append(word2index[w.lower()])
        except KeyError:
            s_int.append(word2index['-OOV-'])
 
    test_sentences_X.append(s_int)
 
for s in train_tags:
    train_tags_y.append([tag2index[t] for t in s])
 
for s in test_tags:
    test_tags_y.append([tag2index[t] for t in s])
 
print(train_sentences_X[0])
print(test_sentences_X[0])
print(train_tags_y[0])
print(test_tags_y[0])

[6169, 842, 4763, 8620, 7926, 4746, 179, 9831, 6765, 6231, 1530, 4679]
[2972, 3889, 9838, 3984, 5397, 1, 6646, 740, 2116, 9394, 5447, 4250, 9838, 740, 1, 8218, 473, 2834, 1125, 5746, 740, 2485, 6244, 9831, 1271, 5347, 4679]
[3, 3, 32, 16, 38, 11, 3, 10, 40, 3, 16, 5]
[20, 20, 46, 36, 34, 11, 10, 40, 16, 17, 38, 25, 46, 40, 25, 38, 11, 2, 37, 10, 40, 25, 16, 10, 17, 38, 5]


In [11]:
MAX_LENGTH = len(max(train_sentences_X, key=len))
print(MAX_LENGTH)

271


In [14]:
import tensorflow
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
 
train_sentences_X = pad_sequences(train_sentences_X, maxlen=MAX_LENGTH, padding='post')
test_sentences_X = pad_sequences(test_sentences_X, maxlen=MAX_LENGTH, padding='post')
train_tags_y = pad_sequences(train_tags_y, maxlen=MAX_LENGTH, padding='post')
test_tags_y = pad_sequences(test_tags_y, maxlen=MAX_LENGTH, padding='post')
 
print(train_sentences_X[0])
print(test_sentences_X[0])
print(train_tags_y[0])
print(test_tags_y[0])

[ 6480  8582  3071   921  9081  6035  5660  7165  6418  8396  3179  4418
  4681  8396  9323 10389  3092   395  8396  3402  1142  5635  4047  3813
  8505     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0   

In [15]:
from keras import backend as K

def ignore_class_accuracy(to_ignore=0):
    def ignore_accuracy(y_true, y_pred):
        y_true_class = K.argmax(y_true, axis=-1)
        y_pred_class = K.argmax(y_pred, axis=-1)
 
        ignore_mask = K.cast(K.not_equal(y_pred_class, to_ignore), 'int32')
        matches = K.cast(K.equal(y_true_class, y_pred_class), 'int32') * ignore_mask
        accuracy = K.sum(matches) / K.maximum(K.sum(ignore_mask), 1)
        return accuracy
    return ignore_accuracy

In [16]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, InputLayer, Bidirectional, TimeDistributed, Embedding, Activation
from keras.optimizers import Adam
 
 
model = Sequential()
model.add(InputLayer(input_shape=(MAX_LENGTH, )))
model.add(Embedding(len(word2index), 128))
model.add(Bidirectional(LSTM(256, return_sequences=True)))
model.add(TimeDistributed(Dense(len(tag2index))))
model.add(Activation('softmax'))
 
model.compile(loss='categorical_crossentropy', optimizer=Adam(0.001), metrics=['accuracy', ignore_class_accuracy(0)])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 271, 128)          1339008   
                                                                 
 bidirectional (Bidirectiona  (None, 271, 512)         788480    
 l)                                                              
                                                                 
 time_distributed (TimeDistr  (None, 271, 47)          24111     
 ibuted)                                                         
                                                                 
 activation (Activation)     (None, 271, 47)           0         
                                                                 
Total params: 2,151,599
Trainable params: 2,151,599
Non-trainable params: 0
_________________________________________________________________


In [17]:
def to_categorical(sequences, categories):
    cat_sequences = []
    for s in sequences:
        cats = []
        for item in s:
            cats.append(np.zeros(categories))
            cats[-1][item] = 1.0
        cat_sequences.append(cats)
    return np.array(cat_sequences)


In [18]:
cat_train_tags_y = to_categorical(train_tags_y, len(tag2index))
print(cat_train_tags_y[0])

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [19]:
model.fit(train_sentences_X, to_categorical(train_tags_y, len(tag2index)), batch_size=128, epochs=40, validation_split=0.15)

Epoch 1/40
23/23 [==============================] - 30s 1s/step - loss: 1.0980 - accuracy: 0.8647 - ignore_accuracy: 0.0315 - val_loss: 0.3514 - val_accuracy: 0.9022 - val_ignore_accuracy: 0.1946
Epoch 2/40
23/23 [==============================] - 27s 1s/step - loss: 0.3223 - accuracy: 0.9107 - ignore_accuracy: 0.1313 - val_loss: 0.3217 - val_accuracy: 0.9096 - val_ignore_accuracy: 0.1305
Epoch 3/40
23/23 [==============================] - 26s 1s/step - loss: 0.3051 - accuracy: 0.9161 - ignore_accuracy: 0.1335 - val_loss: 0.3097 - val_accuracy: 0.9150 - val_ignore_accuracy: 0.1386
Epoch 4/40
23/23 [==============================] - 26s 1s/step - loss: 0.2942 - accuracy: 0.9177 - ignore_accuracy: 0.1347 - val_loss: 0.2996 - val_accuracy: 0.9153 - val_ignore_accuracy: 0.1421
Epoch 5/40
23/23 [==============================] - 26s 1s/step - loss: 0.2840 - accuracy: 0.9191 - ignore_accuracy: 0.1487 - val_loss: 0.2900 - val_accuracy: 0.9172 - val_ignore_accuracy: 0.1597
Epoch 6/40
23/23 [==

In [20]:
scores = model.evaluate(test_sentences_X, to_categorical(test_tags_y, len(tag2index)))
print(f"{model.metrics_names[1]}: {scores[1] * 100}")   

19/19 [==============================] - 3s 174ms/step - loss: 0.0328 - accuracy: 0.9917 - ignore_accuracy: 0.9147
accuracy: 99.17287826538086


In [21]:
def logits_to_tokens(sequences, index):
    token_sequences = []
    for categorical_sequence in sequences:
        token_sequence = []
        for categorical in categorical_sequence:
            token_sequence.append(index[np.argmax(categorical)])
 
        token_sequences.append(token_sequence)
 
    return token_sequences

In [22]:
test_samples = ["running is very important for me".split(), "I was running every day for a month".split()]
test_samples_X = []
for s in test_samples:
    s_int = []
    for w in s:
        try:
            s_int.append(word2index[w.lower()])
        except KeyError:
            s_int.append(word2index['-OOV-'])
    test_samples_X.append(s_int)
 
test_samples_X = pad_sequences(test_samples_X, maxlen=MAX_LENGTH, padding='post')
predictions = model.predict(test_samples_X)

1/1 [==============================] - 1s 610ms/step


In [23]:
logits_to_tokens(predictions, {i: t for t, i in tag2index.items()})[0][:len(test_samples[0])]

['VBG', 'VBZ', 'RB', 'JJ', 'IN', 'PRP']

In [24]:
logits_to_tokens(predictions, {i: t for t, i in tag2index.items()})[1][:len(test_samples[1])]

['PRP', 'VBD', 'VBG', 'DT', 'NN', 'IN', 'DT', 'NN']